-- Crea el schema
DROP SCHEMA IF EXISTS JAZZDATA;
CREATE SCHEMA JAZZDATA ;
USE JAZZDATA;

-- Crea tablas 

CREATE TABLE USUARIO (
  ID_User INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  UserName VARCHAR(25) NOT NULL,
  Nombre VARCHAR(25) NOT NULL,
  EMail VARCHAR(25) NOT NULL,
  Usuario_creacion TIMESTAMP
);

CREATE TABLE MUSICO (
  ID_Musico INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(45) NOT NULL,
  FechaNacimiento DATE NOT NULL,
  FechaMuerte DATE,
  Biografia LONGTEXT,
  Instrumento VARCHAR(15) NOT NULL,
  IMG_dir VARCHAR(15) NOT NULL
);

CREATE TABLE COMPOSITOR (
  ID_Compositor INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(45) NOT NULL,
  FechaNacimiento DATE NOT NULL,
  FechaMuerte DATE,
  Biografia LONGTEXT
);

CREATE TABLE SELLO (
  ID_Sello INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(45) NOT NULL,
  Activo BOOLEAN, 
  Fecha DATE,
  Biografia LONGTEXT
);

CREATE TABLE TRACK (
  ID_Track INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(40) NOT NULL,
  Duracion TIME,
  Compositor INT UNSIGNED NOT NULL,
  FOREIGN KEY (Compositor) REFERENCES COMPOSITOR(ID_Compositor)	
);

CREATE TABLE ALBUM (
  ID_Album INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(35) NOT NULL,
  Fecha DATE NOT NULL,
  Genero VARCHAR(10),
  Critica LONGTEXT,
  IMG_dir VARCHAR(15) NOT NULL,
  Sello INT UNSIGNED NOT NULL,
  FOREIGN KEY (Sello) REFERENCES SELLO(ID_Sello)	
);

-- 

CREATE TABLE TrackMusico (
  ID_TrackMusico INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Musico INT UNSIGNED NOT NULL,
  Track INT UNSIGNED NOT NULL,
  FOREIGN KEY (Musico) REFERENCES MUSICO(ID_Musico),
  FOREIGN KEY (Track) REFERENCES TRACK(ID_Track)
);

CREATE TABLE AlbumTrack (
  ID_AlbumTrack INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  TrackNumber INT,
  Track INT UNSIGNED NOT NULL,
  Album INT UNSIGNED NOT NULL,
  FOREIGN KEY (Track) REFERENCES TRACK(ID_Track),
  FOREIGN KEY (Album) REFERENCES ALBUM(ID_Album)
);

