 -- FUNCION PARA UTILIZAR EN EL CALCULO DE AÑOS, EJ SALIDA DE UN DISCO, AÑOS VIGENTES DE UN SELLO ETC

CREATE FUNCTION `calcular_anios_transcurridos` (fecha DATE) RETURNS INT
NO SQL
BEGIN
DECLARE resultado INT;

SET resultado = TIMESTAMPDIFF(year,fecha, now()); 
RETURN resultado;
END


 -- FUNCION PARA CALCULAR LA CANTIDAD DE ITEMS EN UNA COLUMNA

CREATE FUNCTION `calcular_cantidad` (Item CHAR(30), Columna CHAR(30), Tabla CHAR(30)) RETURNS INT
READS SQL DATA 
BEGIN
DECLARE resultado INT;
SET resultado = (SELECT COUNT(Columna) FROM Tabla WHERE Columna LIKE Item); 
RETURN resultado;
END